### ISSUE TITLE
Error when submitting nested form

### ISSUE THREAD

**Issue by torepettersen** [ash-project/ash_phoenix#128]
**Describe the bug**
My app is crashing when I am trying to submit a nested form.

**To Reproduce**
Create a nested form. In my case, I have a cart with cart items where I would want to change the quantity of the cart items:
```elixir
form =
  cart
  |> Form.for_update(:update,
    api: Api,
    forms: [
      items: [
        type: :list,
        data: cart.items,
        resource: CartItem,
        create_action: :create,
        update_action: :update
      ]
    ]
  )
  |> to_form()
```

Now submitting the data from this form is where it crashes. The params look like like this when the form changes:
```elixir
Form.submit(form, params: %{
  "items" => %{
    "0" => %{
      "_form_type" => "update",
      "_persistent_id" => "0",
      "id" => "018d045e-8413-7dfe-b619-b468328242b3",
      "quantity" => "10"
    },
    "1" => %{
      "_form_type" => "update",
      "_persistent_id" => "1",
      "id" => "018d0e93-3019-75da-948b-8c9ebe60bfdf",
      "quantity" => "20"
    }
  }
})
```

The result is the app crashing with this error:
```elixir
[error] GenServer #PID<0.1482.0> terminating
** (FunctionClauseError) no function clause matching in Puppy.Orders.CartItem.cast_input/2
    (puppy 0.1.0) lib/puppy/orders/resources/cart_item.ex:2: Puppy.Orders.CartItem.cast_input(%{"_form_type" => "update", "_persistent_id" => "1", "id" => "018d0e93-3019-75da-948b-8c9ebe60bfd
f", "quantity" => "20"}, [])
    (ash 2.18.1) lib/ash/type/type.ex:576: Ash.Type.cast_input/3
    (puppy 0.1.0) deps/ash/lib/ash/type/type.ex:1115: anonymous fn/3 in Puppy.Orders.CartItem.cast_input_array/2
    (elixir 1.16.0) lib/enum.ex:4842: Enumerable.List.reduce/3
    (elixir 1.16.0) lib/enum.ex:2582: Enum.reduce_while/3
    (ash 2.18.1) lib/ash/type/helpers.ex:10: Ash.Type.Helpers.cast_input/5
    (ash 2.18.1) lib/ash/changeset/changeset.ex:3784: Ash.Changeset.do_set_argument/3
    (stdlib 5.2) maps.erl:416: :maps.fold_1/4
    (ash 2.18.1) lib/ash/changeset/changeset.ex:1262: Ash.Changeset.handle_params/4
    (ash 2.18.1) lib/ash/changeset/changeset.ex:1196: Ash.Changeset.do_for_action/4
    (ash_phoenix 1.2.26) lib/ash_phoenix/form/form.ex:1096: AshPhoenix.Form.validate/3
    (ash_phoenix 1.2.26) lib/ash_phoenix/form/form.ex:1644: AshPhoenix.Form.submit/2
    (ash_phoenix 1.2.26) lib/ash_phoenix/form/form.ex:1629: AshPhoenix.Form.submit/2
    (puppy 0.1.0) lib/puppy_web/pages/cart_live.ex:63: PuppyWeb.CartLive.handle_event/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/channel.ex:497: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.2.1) /home/tore/workspace/puppy/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/channel.ex:250: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.2) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2) proc_lib.erl:251: :proc_lib.wake_up/3

```

**Expected behavior**
Either that the form will be submitted or an error that is pointing out what I am doing wrong.

**Similar error also happening when adding a form**
`Form.add_form(form, [:items])` crashes with a similar error:
```elixir
[error] #PID<0.567.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.566.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /cart
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Puppy.Orders.CartItem.cast_input/2
        (puppy 0.1.0) lib/puppy/orders/resources/cart_item.ex:2: Puppy.Orders.CartItem.cast_input(%{"_form_type" => "create"}, [])
        (ash 2.18.1) lib/ash/type/type.ex:576: Ash.Type.cast_input/3
        (puppy 0.1.0) deps/ash/lib/ash/type/type.ex:1115: anonymous fn/3 in Puppy.Orders.CartItem.cast_input_array/2
        (elixir 1.16.0) lib/enum.ex:4842: Enumerable.List.reduce/3
        (elixir 1.16.0) lib/enum.ex:2582: Enum.reduce_while/3
        (ash 2.18.1) lib/ash/type/helpers.ex:10: Ash.Type.Helpers.cast_input/5
        (ash 2.18.1) lib/ash/changeset/changeset.ex:3784: Ash.Changeset.do_set_argument/3
        (stdlib 5.2) maps.erl:416: :maps.fold_1/4
        (ash 2.18.1) lib/ash/changeset/changeset.ex:1262: Ash.Changeset.handle_params/4
        (ash 2.18.1) lib/ash/changeset/changeset.ex:1196: Ash.Changeset.do_for_action/4
        (ash_phoenix 1.2.26) lib/ash_phoenix/form/form.ex:1096: AshPhoenix.Form.validate/3
        (puppy 0.1.0) lib/puppy_web/pages/cart_live.ex:29: PuppyWeb.CartLive.mount/3
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/utils.ex:354: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
        (telemetry 1.2.1) /home/tore/workspace/puppy/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/static.ex:281: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/static.ex:116: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.10) lib/phoenix/router.ex:432: Phoenix.Router.__call__/5
        (puppy 0.1.0) lib/puppy_web/endpoint.ex:1: PuppyWeb.Endpoint.plug_builder_call/2
        (puppy 0.1.0) deps/plug/lib/plug/debugger.ex:136: PuppyWeb.Endpoint."call (overridable 3)"/2

```

**Runtime**
 - Elixir version: 1.16.0-otp-26
 - Erlang version: 26.2.1
 - OS: Endeavor OS 2023.08.05
 - Ash version: 2.18.1
 - Ash Phoenix: 1.2.26

**Additional context**

The cart has a relationship to cart items:
```elixir
relationships do
  has_many :items, CartItem
end
```

Update action should also update the cart item:
```elixir
update :update do
  primary? true

  argument :items, {:array, CartItem}

  change manage_relationship(:items, type: :append_and_remove)
end
```

**Comment by zachdaniel** [comment]
So, I could have *sworn* that we had a validation in place to prevent this, but we deprecated using resources as a type like that (except for embedded resources). To do it, you would want to do this (which would be equivalent)

```elixir
argument :items, {:array, :struct} do
  constraints items: [instance_of: CartItem]
end
```

*however* for working with managed relationships (especially with forms), you likely don't want to be requiring that the input is exactly an instance of a struct. You'll want it to be

```elixir
argument :items, {:array, :map}
```

I'm closing this issue, but will be fully removing the underlying `Ash.Type` interface for resources that are not embedded resources in 3.0.

**Comment by torepettersen** [comment]
Thank you for the quick response :heart: 

That solves the issue. I just was not able to get from the error message what I was doing wrong :see_no_evil: 

Yes, absolutely want it to be:
```elixir
argument :items, {:array, :map}
```
