### ISSUE TITLE
Rendering a form for a many-many relationship in an action that accepts an array of IDs crashes

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_phoenix#143]
**Describe the bug**

The form for a resource action that accepts an array of UUIDs for a many-many relationship, crashes before even rendering the form! :(

**To Reproduce**

Main resource (Element):

```elixir
  relationships do 
    many_to_many :competencies, MyApp.Competency,
      source_attribute_on_join_resource: :element_id,
      destination_attribute_on_join_resource: :competency_id,
      through: MyApp.ElementCompetency
  end

  actions do
    create :create do
      primary? true
      argument :competency_ids, {:array, :uuid}
      change manage_relationship(:competency_ids, :competencies, type: :append_and_remove)
    end
```

Join table (ElementCompetency):

```elixir
  relationships do
    belongs_to :element, MyApp.Element
    belongs_to :competency, MyApp.Competency
  end

  actions do
    defaults [:create, :read, :update, :destroy]
  end
```

Many-many relation (Competency):

```elixir
  relationships do
    many_to_many :elements, MyApp.Element,
      source_attribute_on_join_resource: :competency_id,
      destination_attribute_on_join_resource: :element_id,
      through: MyApp.ElementCompetency
  end

  actions do
    defaults [:create, :read, :update, :destroy]
  end
```

Rendering the form for the Element `create` action raises the following error - 

```
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: [{:join, :destroy, []}]
        (ash_phoenix 1.3.4) lib/ash_phoenix/form/auto.ex:613: AshPhoenix.Form.Auto.add_destroy_action/4
        (ash_phoenix 1.3.4) lib/ash_phoenix/form/auto.ex:382: anonymous fn/4 in AshPhoenix.Form.Auto.related/3
        (ash_phoenix 1.3.4) lib/ash_phoenix/form/form.ex:3224: anonymous fn/1 in AshPhoenix.Form.update_opts/3
        (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
        (elixir 1.15.4) lib/keyword.ex:1107: Keyword.update!/4
        (elixir 1.15.4) lib/keyword.ex:1111: Keyword.update!/4
        (ash_phoenix 1.3.4) lib/ash_phoenix/form/form.ex:441: AshPhoenix.Form.for_create/3
        (ash_admin 0.10.7) lib/ash_admin/components/resource/form.ex:1620: AshAdmin.Components.Resource.Form.assign_form/1
        (ash_admin 0.10.7) lib/ash_admin/components/resource/form.ex:37: AshAdmin.Components.Resource.Form.update/2
        (phoenix_live_view 0.20.14) lib/phoenix_live_view/utils.ex:498: Phoenix.LiveView.Utils.maybe_call_update!/3
        (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
        (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:685: anonymous fn/4 in Phoenix.LiveView.Diff.render_pending_components/6
        (telemetry 1.2.1) /Users/rebecca/Projects/work/my_client/my_app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:680: anonymous fn/4 in Phoenix.LiveView.Diff.render_pending_components/6
        (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
        (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:639: Phoenix.LiveView.Diff.render_pending_components/6
        (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:143: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.20.14) lib/phoenix_live_view/static.ex:249: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.20.14) lib/phoenix_live_view/static.ex:132: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.20.14) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
```

**Runtime**

 - Elixir version 1.15.4-otp-26
 - Erlang version 26.0.2
 - OS macOS Sonoma 
 - Ash version 2.20.1
 - AshAdmin 0.10.7

**Comment by zachdaniel** [comment]
Looks like a straightforward pattern matching issue, please let me know if the issue persists after trying `main` 🙇

**Comment by sevenseacat** [comment]
Thanks for the quick fix! Apologies for filing it in the wrong place, I should have read the error message more closely 🙈

**Comment by zachdaniel** [comment]
Not a problem at all :) Its definitely hard to tell sometimes w/ Ash packages 😆
